import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const sabon = localFont({
  src: [
    { path: "./fonts/sabon/Sabon.ttf", weight: "400", style: "normal" },
    { path: "./fonts/sabon/SabonItalic.ttf", weight: "400", style: "italic" },
    { path: "./fonts/sabon/SabonBold.ttf", weight: "700", style: "normal" },
    { path: "./fonts/sabon/SabonBoldItalic.ttf", weight: "700", style: "italic" },
  ],
  variable: "--font-sabon",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${sabon.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
